### ISSUE TITLE
MA 报错，图片load不出来

### ISSUE THREAD

**Issue by greenhandzdl** [gsycl2004/WordCloudPlugin#1]
![Screenshot_20220131_131612_io github mzdluo123 mirai android](https://user-images.githubusercontent.com/61241103/151743740-7cb869fc-7a95-437a-aeaf-574a0e639366.jpg)

**Comment by myot233** [comment]
这个应该是结巴分词的问题

**Comment by myot233** [comment]
你尝试一下新发的版本

**Comment by greenhandzdl** [comment]
那个，大佬，还是不行
![7455DE468633D59D6552CB46CAB4D392](https://user-images.githubusercontent.com/61241103/153162124-6a9a4b23-bdca-42fb-ad0e-541c45e3f894.jpg)
![86CB897317A87247BDCA6F7012498A23](https://user-images.githubusercontent.com/61241103/153162135-703b87ef-480d-4b1c-90e8-f54c46396c52.jpg)
依赖：
![image](https://user-images.githubusercontent.com/61241103/153162325-ed56db4a-e734-4412-bafa-c3ca8d2cd2e7.png)
还有git版本：
![image](https://user-images.githubusercontent.com/61241103/153162437-f7059ac9-fef2-44d6-a208-4439e43a051e.png)

**Comment by myot233** [comment]
看log好像是分词器的字典找不到了

**Comment by greenhandzdl** [comment]
可能吧，感觉MA最近更新更不上来了，或许得尝试MA之外的套娃
